### ISSUE TITLE
Stuck recompressing .jar

### ISSUE THREAD

**Issue by ArinoJenynof** [nicolas-comerci/precomp-cpp#3]
Hello, i just want to report something that i found. Hope you don't mind, seeing that you're in the middle of refactoring precomp.

Using master (at the time of writing 8bdb908), precomp stuck processing PlantVsZombies.jar. It's a J2ME game, you can get it from [Kahvibreak](https://bluemaxima.org/kahvibreak/). I made some experiment, and here's what i found:

## What i did when building
I used the UCRT environment of MSYS2 to build. Hopefully it's okay to build statically.
```bash
cmake -B build -DCMAKE_EXE_LINKER_FLAGS=-static -DCMAKE_SHARED_LINKER_FLAGS=-static
cmake --build build
```

## Command
This are the command that i used with precomp, both the one that i build and the v0.2a from release
```bash
precomp.exe -e -v -vstderr -intense -brute PlantVsZombies.jar 2>out.txt
```
Both are stuck
[precomp-master.txt](https://github.com/nicolas-comerci/precomp-cpp/files/12262037/precomp-master.txt)
[precomp048-02a.txt](https://github.com/nicolas-comerci/precomp-cpp/files/12262046/precomp048-02a.txt)

Using `-d0` switch makes precomp able to process the .jar
[precomp-master-d0.txt](https://github.com/nicolas-comerci/precomp-cpp/files/12262100/precomp-master-d0.txt)
[precomp048-02a-d0.txt](https://github.com/nicolas-comerci/precomp-cpp/files/12262102/precomp048-02a-d0.txt)

## Comparison with precomp 0.4.7
I also tested with precomp 0.4.7 to see how it goes there. Command is almost the same except for the `-cn` switch. Precomp 0.4.7 succesfully processed the file, even without `-d0` switch.
[precomp047.txt](https://github.com/nicolas-comerci/precomp-cpp/files/12262180/precomp047.txt)

And that's it. Hopefully this is a useful report 😅
Let me know if you need anything else

**Comment by nicolas-comerci** [comment]
Interesting. I have already seen Precomp stuck during precompression and have some samples, but this report does give me another useful sample to test.
It's pretty ironic to tell you the truth, as recompression on Precomp Neo uses concurrency and I was worried if I made a mistake on it, it could end up on recompression getting stuck because of a deadlock.
But so far I have only see it happen during precompression.

I'm close to finishing the new refactoring effort to unify the different format handlers behavior, so that it's easier to take some measures to ensure data is properly precompressed (namely, I want to add a `--verify` option that ensures recompression won't fail/recover bad data, and just reject the stream and store it uncompressed if recompression would fail)

But as soon as I am done with that my priority will be reliability+stability, so reports like this are very useful, thanks!

**Comment by nicolas-comerci** [comment]
@ArinoJenynof v0.4a fixes the hang in PlantVsZombies.jar, please confirm for yourself.

I have however already gathered some other problematic samples included in Kahvibreak, so it seems like a good lead to continue hunting bugs, I will continue to do so whenever I have the time.

**Comment by ArinoJenynof** [comment]
Yes, just confirmed it, thank you very much. Looks like it was right to report after all, you even get other problematic samples 😀

Gonna close this issue myself, if you don't mind.
